### ISSUE TITLE
setting SONAR_SCANNER_HOME as property

### ISSUE THREAD

**Issue by yoeluk** [mwz/sbt-sonar#1]
SONAR_SCANNER_HOME can only be set as an env variable and this causes quite a bit of issues in a build pipeline where you don't necessarily have that much control. Such that I can't set it at all and can't use it an similar build server to the bitbucket pipeline. If I could set it as a property that would be much easier.

Thanks for the plugin!

**Comment by mwz** [comment]
Implemented in https://github.com/mwz/sbt-sonar/pull/2 and released in `1.1.0`.
