### ISSUE TITLE
sonar.scoverage.reportPath was deprecated in sonar-scala 6.2.0

### ISSUE THREAD

**Issue by mwz** [mwz/sbt-sonar#11]
The Scoverage report path property `sonar.scoverage.reportPath` was deprecated in sonar-scala [6.2.0](https://github.com/mwz/sonar-scala/releases/tag/v6.2.0) and we should use the new property`sonar.scala.scoverage.reportPath` instead.

**Comment by manodupont** [comment]
Is this on ?!!?

**Comment by mwz** [comment]
It's a super tiny change, pretty much find `sonar.scoverage.reportPath` and replace with `sonar.scala.scoverage.reportPath` across the project. If that's something you could contribute it would be great, otherwise I can make that change.

**Comment by mwz** [comment]
Implemented in #30.
