### ISSUE TITLE
Support Server authentication token

### ISSUE THREAD

**Issue by if54uran** [mwz/sbt-sonar#130]
By now sbt-sonar does not seem to support "Server authentication token" that are provided by "SonarQube servers" from jenkins.

Did I miss something?

**Comment by mwz** [comment]
Hi, do you mean the [user token](https://docs.sonarqube.org/latest/user-guide/user-token) or something else?

**Comment by if54uran** [comment]
Yes that is what I mean. Our Jenkins Server injects it as an enviroment variable which is picked up by all the Java projects using the "hudson.plugins.sonar". Because of the fact that this does not work with sbt-sonar and that I can not find any documentation about it I concluded that it is not supported. Is that correct?
