### ISSUE TITLE
sbt task sonarScan: Cannot run program '.*\bin\sonar-scanner' on windows

### ISSUE THREAD

**Issue by HemantManglani** [mwz/sbt-sonar#15]
I get an error when I try to execute sbt task sonarScan

[error] (sonarScan) java.io.IOException: Cannot run program "%SONAR_SCANNER_HOME%\bin\sonar-scanner": CreateProcess error=2, The system cannot find the file specified

I have created 'SONAR_SCANNER_HOME' environment variable. sonar-scanner.bat does exists under mentioned path; but it still complains.

I think the issue with this piece of code:
val sonarScanner = Paths.get(sonarHome).resolve("bin/**sonar-scanner**").toAbsolutePath.toString

Using:
sbt-sonar: v1.4.0
sonar-scanner: sonar-scanner-3.2.0.1227-windows

**Comment by mwz** [comment]
Hi @HemantManglani, thanks for raising this issue.

Looks like you are right and this obviously isn't going to work on Windows - majority of the users use UNIX-like OSes, so this has never been an issue before.

This looks like an easy fix and I guess we should try replacing `resolve("bin/sonar-scanner")` with `resolve("bin", "sonar-scanner")`, unless specifying the extention is also necessary, in which case we can introduce a Windows check (similar to e.g. https://github.com/sbt/sbt/blob/4c3cd4e535a89d220a0d20f360f36212ceff9b09/internal/util-collection/src/main/scala/sbt/internal/util/Util.scala#L46).

I'm afraid I don't have Windows to test this, would you be interesting in contributing the change yourself?

**Comment by mwz** [comment]
Hi @HemantManglani, `1.5.0` is out with a fix by @Bolt54 - would you like to give it a go?
