### ISSUE TITLE
Improved usage/getting started documentation

### ISSUE THREAD

**Issue by rohdef** [mwz/sbt-sonar#22]
First off, great project, thanks for the awesome work you have done :+1: 

However, the learning curve was rather steep. My initial project/build.properties had sbt.version set to 1.2.1 which doesn't seem to work (is that due to: `crossSbtVersions := Seq("0.13.17", "1.1.6")`?). At least it seems to work with both 0.13.17 and 1.1.6. If a correct version is a requirement that would be nice to know.

As I ran in to your plugin fairly early in my Scala learning process (well tools like these are good for learning good practices) I'm far from experienced in sbt, I was confused about where to put the `sonarProperties ++= Map(...`, seems that build.sbt is the right place, although googling also showed that I can do something like build.sonar.sbt :) That would probably be a very helpful addition to other newcomers.

Having a fully working minimal example of the use would be a very nice addition. Could be in a folder named examples, or something similar.

I think that was my getting started observations. Once again, thanks a lot for this great project

**Comment by rohdef** [comment]
Oh yeah, forgot, also please add how to properly set `SONAR_SCANNER_HOME` and `sonarScanner.home`. Never got `SONAR_SCANNER_HOME` to work (is it a bash environment variable? If so, it doesn't seem to work for me). So far only way I got that part to work is:

`sbt -DsonarScanner.home=/home/rohdef/Programs/sonar-scanner-3.2.0.1227-linux sonarScan`

Is that really the right way?

**Comment by mwz** [comment]
Hi @rohdef and thanks for your feedback.

> My initial project/build.properties had sbt.version set to 1.2.1 which doesn't seem to work (is that due to: `crossSbtVersions := Seq("0.13.17", "1.1.6")`?). At least it seems to work with both 0.13.17 and 1.1.6. If a correct version is a requirement that would be nice to know.

That's interesting - I've used this plugin with `1.2.1` without any issues - it would be good to see what error you're getting - feel free to create a new issue about this and I'll be happy to take a look.

> As I ran in to your plugin fairly early in my Scala learning process (well tools like these are good for learning good practices) I'm far from experienced in sbt, I was confused about where to put the `sonarProperties ++= Map(...`, seems that build.sbt is the right place, although googling also showed that I can do something like build.sonar.sbt :) That would probably be a very helpful addition to other newcomers.

You should definitely check out sbt documentation, but yes, those settings should be added to your `build.sbt` file along with the imports listed in the README.

> Having a fully working minimal example of the use would be a very nice addition. Could be in a folder named examples, or something similar.

The examples are in the [src/sbt-test](https://github.com/mwz/sbt-sonar/tree/master/src/sbt-test/sbt-sonar) directory, but I will link them somewhere in the README so it's easier to find them :+1: 

> Never got `SONAR_SCANNER_HOME` to work (is it a bash environment variable?

Yes, this is an environment variable which needs to be exported in your shell before running the analysis. If you use bash you can export it in your `.bashrc` or `.profile` files:
```bash
export SONAR_SCANNER_HOME=~/Programs/sonar-scanner-3.2.0.1227-linux
```
Your example will also work, but it's easier to have it set as an environment variable because you only have to do it once. 
Btw, this won't be necessary in the next major version as we'll use an embedded sonar scanner which doesn't require `sonar-scanner-cli`, but for now you have to do this.

**Comment by rohdef** [comment]
> Hi @rohdef and thanks for your feedback.
> 
> > My initial project/build.properties had sbt.version set to 1.2.1 which doesn't seem to work (is that due to: `crossSbtVersions := Seq("0.13.17", "1.1.6")`?). At least it seems to work with both 0.13.17 and 1.1.6. If a correct version is a requirement that would be nice to know.
> 
> That's interesting - I've used this plugin with `1.2.1` without any issues - it would be good to see what error you're getting - feel free to create a new issue about this and I'll be happy to take a look.

Strange I cannot reproduce that anymore, must have been a fluke in the IntelliJ setup, I guess we can ignore that issue then :)


> > As I ran in to your plugin fairly early in my Scala learning process (well tools like these are good for learning good practices) I'm far from experienced in sbt, I was confused about where to put the `sonarProperties ++= Map(...`, seems that build.sbt is the right place, although googling also showed that I can do something like build.sonar.sbt :) That would probably be a very helpful addition to other newcomers.
> 
> You should definitely check out sbt documentation, but yes, those settings should be added to your `build.sbt` file along with the imports listed in the README.

Will definitely do in due time :) It feels like I'm learning a million new things right now ;)

 
> > Having a fully working minimal example of the use would be a very nice addition. Could be in a folder named examples, or something similar.
> 
> The examples are in the [src/sbt-test](https://github.com/mwz/sbt-sonar/tree/master/src/sbt-test/sbt-sonar) directory, but I will link them somewhere in the README so it's easier to find them 

Indeed, and I found those after a while, but for instance there's no configuration in build.sbt apart from the addSbtPlugin, which caused me to be confused about where to place the `sonarProperties` part :) And also it would be perfect if it is a bit like:

```
    sonarProperties ++= Map(
      "sonar.scala.version" -> "2.12.",
      "sonar.projectName" -> "something fancy",
      "sonar.projectKey" -> "fancy-proj",
      "sonar.sources" -> "src/main/scala",
      "sonar.host.url" -> "http://localhost:9000"
    )
```

I suspect that's what most would want to use (e.g., I wouldn't like the host to be specified by sonar scanner, and per your comment later it soon won't be needed any more - I look forward to that :+1: )


> > Never got `SONAR_SCANNER_HOME` to work (is it a bash environment variable?
> 
> Yes, this is an environment variable which needs to be exported in your shell before running the analysis. If you use bash you can export it in your `.bashrc` or `.profile` files:
> 
> ```shell
> export SONAR_SCANNER_HOME=~/Programs/sonar-scanner-3.2.0.1227-linux
> ```
> 
> Your example will also work, but it's easier to have it set as an environment variable because you only have to do it once.
> Btw, this won't be necessary in the next major version as we'll use an embedded sonar scanner which doesn't require `sonar-scanner-cli`, but for now you have to do this.

Strange, if I run the following:

```
rohdef@josefine:~/IdeaProjects/ticket-server$ echo $SONAR_SCANNER_HOME 
/home/rohdef/Programs/sonar-scanner-3.2.0.1227-linux
rohdef@josefine:~/IdeaProjects/ticket-server$ sbt sonarScan
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /home/rohdef/.sbt/1.0/plugins
[info] Loading settings for project ticket-server-build from plugins.sbt ...
[info] Loading project definition from /home/rohdef/IdeaProjects/ticket-server/project
[info] Loading settings for project ticket-server from build.sbt,build.sonar.sbt ...
[info] Set current project to ticket-server (in build file:/home/rohdef/IdeaProjects/ticket-server/)
[error] java.lang.RuntimeException: SONAR_SCANNER_HOME environment variable or sonarScanner.home system property not defined.
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbtsonar.SonarPlugin$.$anonfun$projectSettings$5(SonarPlugin.scala:57)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at sbtsonar.SonarPlugin$.$anonfun$projectSettings$3(SonarPlugin.scala:56)
[error]         at sbtsonar.SonarPlugin$.$anonfun$projectSettings$3$adapted(SonarPlugin.scala:49)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (sonarScan) SONAR_SCANNER_HOME environment variable or sonarScanner.home system property not defined.
[error] Total time: 0 s, completed Dec 16, 2018, 4:41:25 PM
rohdef@josefine:~/IdeaProjects/scala-proj$ 
```

I would say it should work but, if it's irrelevant from the next version it's probably not worth the time

**Comment by mwz** [comment]
That's strange - it looks like your env variable for some reason isn't correctly picked up by sbt. To see what env variables you have available in sbt, you can run `eval sys.env` in `sbt shell` - hopefully that will help you to figure out what is going on.
