### ISSUE TITLE
I have lots of unresolved dependencies

### ISSUE THREAD

**Issue by manodupont** [mwz/sbt-sonar#27]
on ```sbt sonarScan```

it always fails few seconds after doing great, because of this

ERROR: com.mwz.sonar.scala.scalastyle.ScalastyleSensor has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public com.mwz.sonar.scala.scalastyle.ScalastyleSensor(org.sonar.api.profiles.RulesProfile,com.mwz.sonar.scala.scalastyle.ScalastyleCheckerAPI)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@67a056f1:112<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@35a3d49f:462<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@2c768ada:52<|

Can we "bypass" these ?!

**Comment by mwz** [comment]
Hi @manodupont, which version of sonar-scala and SonarQube are you using?

**Comment by manodupont** [comment]
Used older version of SonarQube : 7.4.
