### ISSUE TITLE
scoverage report upload doesn't work

### ISSUE THREAD

**Issue by manodupont** [mwz/sbt-sonar#29]
`sbt sonarScan` doesn't seem to upload my generated report to sonar.

I did generate my scoverage report using `sbt clean coverage test` as in the doc of scoverage.

I also already have a working `sbt sonarScan` task which uploads all the analysis to SonarQube.

But i can't seem to se my scoverage report uploaded correctly. Values are null for scala coverage.
But if i open the report locally there are indeed some datas .

I tried many configuration for the reportPaths.

HEre is the latest

```
lazy val sonarSettings = Seq(
  sonarProperties ++= Map(
    "sonar.projectName" -> "myproject",
    "sonar.modules" -> "module1,module2,module3",
    "sonar.skippedModules" -> ".",
    "sonar.scala.scoverage.reportPaths" -> "target/scoverage-report/scoverage.xml",
  )
)

```

I also tried with `sbt coverageAggregate`  then the conf would theorically be
```
lazy val sonarSettings = Seq(
  sonarProperties ++= Map(
    "sonar.projectName" -> "myproject",
    "sonar.modules" -> "module1,module2,module3",
    "sonar.skippedModules" -> ".",
    "sonar.scala.scoverage.reportPaths" -> "target/scala-2.12/scoverage-report/scoverage.xml",
  )
)
```

Any idea on this one ?

**Comment by mwz** [comment]
Hi @manodupont, if you're using `sonar-scala` then the name of the property is `sonar.scala.scoverage.reportPath`, but you have an extra `s` at the end. Hope that fixes it.

**Comment by manodupont** [comment]
But it still doesn’t work though.

I don’t see any errors or anything telling me that its working, or not.!

Even though I see there is something under "target/scala-2.12/scoverage-report/scoverage.xml”

Is there any logs I can check ?!?!


On 23 Apr 2019, at 17:51, Michael Wizner <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @manodupont, if you're using sonar-scala then the name of the property is sonar.scala.scoverage.reportPath, but you have an extra s at the end. Hope that fixes it.

**Comment by manodupont** [comment]
Also, based on the doc, it does take an ’s’

https://docs.sonarqube.org/display/PLUG/Scala+Coverage+Results+Import


On 23 Apr 2019, at 17:51, Michael Wizner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @manodupont<https://github.com/manodupont>, if you're using sonar-scala then the name of the property is sonar.scala.scoverage.reportPath, but you have an extra s at the end. Hope that fixes it.

**Comment by BalmungSan** [comment]
You may try using `sonar-scanner` manually with the **-X** _flag_ to see full logs.

You may paste them here if you want. :wink:

**Comment by manodupont** [comment]
Man, i just can't find the problem! To be honest, something is missing in that plugin. 

1 - I got my report under `target/scala-2.12/scoverage-report/scoverage.xml`
2 - i run `sbt sonarScan`
3 - It should just upload the file then ...


?

My conf has 4 lines. I dont get why i need to configure more than that considering the fact that I already have my scoverage.xml created. So the plugin should just have to read that file, and upload it. Which is not ....

Is there a log saying something like: File `target/scala-2.12/scoverage-report/scoverage.xml` being uploaded ... in sonar-scanner ?

**Comment by manodupont** [comment]
Actually you know what ?! 

do i need this ?!?!?! https://github.com/RadoBuransky/sonar-scoverage-plugin/releases

?

**Comment by manodupont** [comment]
Regarding some other issues 

i should see something like that `ERROR: [scoverage] Report not found at /Users/username/Development/projectFolder/module-1/target/scala-2.12/scoverage-report
WARN: [scoverage] Report path not set for Module 1 module! [Module 1.sonar.scoverage.reportPath]`

But i never did ...

**Comment by BalmungSan** [comment]
The thing is, you are using the official SonarQube plugin.
If you do not see any error message even with the debug flag, then I doubt this has to do with this scanner, and probably is something related with the plugin itself.
You may try asking in SonarSource.

Or you may try our custom sonar-scala plugin. _(the one @mwz linked at the beginning)_.

**Comment by manodupont** [comment]
I think its related with my sonar properties multi-module and coverAggregate!

CAuse when i go in sonarQube and set the "Test" key for the Scala Coverage plugin, now i can see something going on when i launch `sbt sonarScan`

Any idea on this one !

<img width="1413" alt="Screenshot 2019-04-12 at 11 44 24" src="https://user-images.githubusercontent.com/7568033/58028235-9757f180-7b1a-11e9-945b-8455037a1b55.png">

What about this ?
```
[info] INFO: Importing coverage from /Users/manueldupont/marche-expertise/target/scala-2.12/scoverage-report/scoverage.xml
[info] WARN: Fail to resolve 212 file(s). No coverage data will be imported on the following file(s): /Users/manueldupont/marche-expertise/covea-ren-impl/src/main/scala/com/darva/covea/ren/CoveaRenJsonSerializerRegistry.scala;/Users/manueldupont/marche-expertise/covea-ren-impl/src/main/scala/com/darva/covea/ren/Cove
```

**Comment by mwz** [comment]
Hi @manodupont, did you manage to get to the bottom of your issue?
