### ISSUE TITLE
Have you seen this?

### ISSUE THREAD

**Issue by ChocPanda** [mwz/sbt-sonar#33]
I highly doubt this has anything to do with the sbt plugin and is likely an error in the travis ci addon however I was wondering if you had experienced the issue I raised here. I started to see it when I updated to the latest release of sbt-sonar (1.7.0) https://travis-ci.community/t/sonar-addon-doesnt-set-environment-variables/3654?u=chocpanda

**Comment by mwz** [comment]
The `SONAR_SCANNER_HOME` environment variable isn't exported by the plugin, as you say in your issue, but it's used by it to call through to `sonar-scanner` cli. You should set the environment variable yourself. Once #19 is implemented it will no longer be needed to have the sonar-scanner cli installed on your server.
