### ISSUE TITLE
sonar.scala.scoverage.reportPath not honored

### ISSUE THREAD

**Issue by britindrelie** [mwz/sbt-sonar#67]
After much trial and error as to why my project would not find reports generated by scoverage, I discovered that the property `sonar.scala.coverage.reportPaths` worked, whereas the property `sonar.scala.scoverage.reportPath`, as written in documentation, did not.

For reference this is a scala 2.12 project, using sbt-sonar 2.1.0 and sbt-scoverage 1.6.0

**Comment by mwz** [comment]
It depends on which Scala plugin you use. In short:
- [sonar-scala](https://github.com/mwz/sonar-scala) uses `sonar.scala.scoverage.reportPath`
- and [SonarScala](https://www.sonarsource.com/products/codeanalyzers/sonarscala.html) uses `sonar.scala.coverage.reportPaths`

There is a PR in the works from @stefanerwinmayer (#45), which will make it easier to switch between those two plugins and have the default properties set automatically.
